### ISSUE TITLE
MQTTClient imports MQTTSessionManager directly

### ISSUE THREAD

**Issue by ogres** [novastone-media/MQTT-Client-Framework#429]
Hello,

After updating to 0.11.0 I got a compilation error because of missing `MQTTSessionManager.h` file.

I am using `'MQTTClient/Min'` , min does not include `MQTTSessionManager`, but `MQTTClient.h` tries to import it anyway.

Its easily reproducible on a fresh project, 

- `pod init`
- add `pod 'MQTTClient/Min'`
- `pod install`

Then open Workspace, import MQTTClient and press compile.

Solution would be to add compilation directives, to only import `MQTTSessionManager` when its available.

**Comment by jcavar** [comment]
Thanks, you are right yes. This should have been caught on CocoaPods publish but I think I disabled that check and it went through.

Sorry about this, will try to fix it as soon as possible.

**Comment by jcavar** [comment]
Fixed by https://github.com/novastone-media/MQTT-Client-Framework/commit/1d094841a5bbc49a8a8ef69e5f8bc9a4e65ce6f6 and https://github.com/novastone-media/MQTT-Client-Framework/commit/6eff8d5e8569305435474e147d4eac1c1b562677

Will release to CocoaPods soon.

**Comment by jcavar** [comment]
Released 0.12.0

**Comment by ogres** [comment]
Thank you!
